behaviors:
    DriveBehavior:
        trainer_type: ppo
        hyperparameters:
            batch_size: 128
            buffer_size: 12800
            learning_rate: 0.0003
            beta: 0.005
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
            learning_rate_schedule: linear
        network_settings:
            normalize: true
            hidden_units: 256
            num_layers: 2
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
            curiosity:
                strength: 0.02
                gamma: 0.99
                encoding_size: 256
                learning_rate: 3.0e-4
        keep_checkpoints: 5
        max_steps: 200000
        time_horizon: 128
        summary_freq: 500
        threaded: true
environment_parameters:
    RoadNumber:
        curriculum:
            -   name: Lesson0 # This is the start of the first lesson
                completion_criteria:
                    measure: reward
                    behavior: DriveBehavior
                    signal_smoothing: true
                    min_lesson_length: 10000
                    threshold: 1
                value: 1
            -   name: Lesson1
                completion_criteria:
                    measure: reward
                    behavior: DriveBehavior
                    signal_smoothing: true
                    min_lesson_length: 10000
                    threshold: 1
                value: 2
            -   name: Lesson2
                completion_criteria:
                    measure: reward
                    behavior: DriveBehavior
                    signal_smoothing: true
                    min_lesson_length: 100
                    threshold: 1
                value: 3